fips = {
    "statefp": {
        "42": "Pennsylvania",
    },
    "lsad": {
        "00": "Blank",
        "20": "barrio",
        "21": "borough",
        "22": "census county division",
        "23": "census subarea",
        "24": "census subdistrict",
        "25": "city",
        "26": "county",
        "27": "district",
        "28": "District (prefix)",
        "29": "precinct",
        "30": "Precinct (prefix)",
        "31": "gore",
        "32": "grant",
        "36": "location",
        "39": "plantation",
        "41": "barrio-pueblo",
        "42": "purchase",
        "43": "town",
        "44": "township",
        "45": "Township (prefix)",
        "46": "Unorganized Territory (UT)",
        "47": "village",
        "49": "charter township",
        "86": "Reservation"
    },
    "classfp": {
        "C2":  "An active incorporated place that is legally coextensive with an county subdivision but treated as independent of any county subdivision",
        "C5":   "An active incorporated place that is independent of any county subdivision and serves as a county subdivision equivalent",
        "C7":   "An incorporated place that is independent of any county",
        "S1":   "A nonfunctioning county subdivision that is coextensive with a census designated place",
        "S2":   "A statistical county subdivision that is coextensive with a census designated place",
        "S3":   "A statistical county subdivision that is coextensive with a legal American Indian, Alaska Native, or Native Hawaiian area",
        "T1":   "An active county subdivision that is not coextensive with an incorporated place",
        "T2":   "An active county subdivision that is coextensive with a census designated place",
        "T5":   "An active county subdivision that is coextensive with an incorporated place",
        "T9":   "An inactive county subdivision",
        "Z1":   "A nonfunctioning county subdivision",
        "Z2":   "A county subdivision that is coextensive with an American Indian, Alaska Native, or Native Hawaiian area and legally is independent of any other county subdivision",
        "Z3":   "A county subdivision defined as an unorganized territory",
        "Z5":   "A statistical county subdivision",
        "Z7":   "A county subdivision that is coextensive with a county or equivalent feature or all or part of an incorporated place that the Census Bureau recognizes separately",
        "Z9":   "Area of a county or equivalent, generally in territorial sea, where no county subdivision exists",
    },
    "mtfcc": {
        "G4040": "County Subdivision",
        "G5420": "School District",
        "G5200": "Congressional District"
    },
    "funcstat": {
        "A":   "Active government providing primary general-purpose functions",
        "B":   "Active government that is partially consolidated with another government but with separate officials providing primary general-purpose functions",
        "C":   "Active government consolidated with another government with a single set of officials",
        "E":   "NEED TO FIGURE OUT",
        "F":   "Fictitious entity created to fill the Census Bureau geographic hierarchy",
        "G":   "Active government that is subordinate to another unit of government.",
        "I":   "Inactive governmental unit that has the power to provide primary special-purpose functions",
        "N":   "Nonfunctioning legal entity",
        "S":   "Statistical entity",
    }
}
